# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-experimental',
                'doc_host': 'https://ndendic.github.io',
                'git_url': 'https://github.com/ndendic/nbdev-experimental',
                'lib_path': 'nbdev_experimental'},
  'syms': {'nbdev_experimental.core': {'nbdev_experimental.core.foo': ('core.html#foo', 'nbdev_experimental/core.py')}}}
